### ISSUE TITLE
cant access data from yahoo

### ISSUE THREAD

**Issue by osheenn** [jmportilla/Udemy-notes#1]
as per your lectures on stock market analysis project i opened up data reader to access stock data from google but unfortunately it shows the following error-OSError: after 3 tries, Yahoo! did not return a 200 for url 'http://ichart.finance.yahoo.com/table.csv?s=AAPL&a=11&b=23&c=2015&d=11&e=23&f=2014&g=d&ignore=.csv'

please help me solve the issue

**Comment by jmportilla** [comment]
Hi Osheenn,

Please post a discussion in the course. In the meantime, check to make sure your firewall is off (this may be blocking pandas)

You can also try downloading and using pandas new data_reader:

http://pandas.pydata.org/pandas-docs/stable/remote_data.html

**Comment by osheenn** [comment]
thanks for the solution i will try to implement it and discuss it with you
asap
